// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5r_fFPi5UQkqfsJx-mbrB5LUUjflzdkk',
    appId: '1:1071532157501:web:3439785dfc4d84f50a9854',
    messagingSenderId: '1071532157501',
    projectId: 'kranti-33825',
    authDomain: 'kranti-33825.firebaseapp.com',
    storageBucket: 'kranti-33825.appspot.com',
    measurementId: 'G-JEN73QDCPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9onNlnWcrXmnJRfNP7cqYfF3FMnjs26A',
    appId: '1:1071532157501:android:05fb4bb737d783520a9854',
    messagingSenderId: '1071532157501',
    projectId: 'kranti-33825',
    storageBucket: 'kranti-33825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI7F0VHff1wXOOhHmRiNCPNK5Y2eVxJdM',
    appId: '1:1071532157501:ios:2df53472076346680a9854',
    messagingSenderId: '1071532157501',
    projectId: 'kranti-33825',
    storageBucket: 'kranti-33825.appspot.com',
    iosBundleId: 'com.example.register',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI7F0VHff1wXOOhHmRiNCPNK5Y2eVxJdM',
    appId: '1:1071532157501:ios:2df53472076346680a9854',
    messagingSenderId: '1071532157501',
    projectId: 'kranti-33825',
    storageBucket: 'kranti-33825.appspot.com',
    iosBundleId: 'com.example.register',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5r_fFPi5UQkqfsJx-mbrB5LUUjflzdkk',
    appId: '1:1071532157501:web:6941b48a4c62e7720a9854',
    messagingSenderId: '1071532157501',
    projectId: 'kranti-33825',
    authDomain: 'kranti-33825.firebaseapp.com',
    storageBucket: 'kranti-33825.appspot.com',
    measurementId: 'G-T74FG9B1HJ',
  );
}
